stages:
  prepare:
    cmd: python src/preprocessing.py
    deps:
      - data/breast_cancer.csv
      - src/preprocessing.py
      - params.yaml
    outs:
      - data/pipeline.pkl
      - data/best_cancer_processed_train_data.csv
      - data/best_cancer_processed_test_data.csv
    params: 
      - features.chi2percentile
      - features.data_path
      - features.target_str
      - features.test_size
      - features.random_state
